### ISSUE TITLE
loader constraint violation for org.apache.avro.Schema when using ParquetFileReader

### ISSUE THREAD

**Issue by jkulzick** [mmolimar/kafka-connect-fs#15]
I'm receiving the below error when using `'file_reader.class': 'com.github.mmolimar.kafka.connect.fs.file.reader.ParquetFileReader'`.

I'm not sure if its related to 
[this change](https://github.com/confluentinc/schema-registry/blame/master/avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java#L19) in `io.confluent.connect.avro.AvroData`

```
java.lang.LinkageError: loader constraint violation: when resolving method "io.confluent.connect.avro.AvroData.toConnectData(Lorg/apache/avro/Schema;Ljava/lang/Object;)Lorg/apache/kafka/connect/data/SchemaAndValue;" the class loader (instance of org/apache/kafka/connect/runtime/isolation/PluginClassLoader) of the current class, com/github/mmolimar/kafka/connect/fs/file/reader/ParquetFileReader$GenericRecordToStruct, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, io/confluent/connect/avro/AvroData, have different Class objects for the type org/apache/avro/Schema used in the signature
        at com.github.mmolimar.kafka.connect.fs.file.reader.ParquetFileReader$GenericRecordToStruct.apply(ParquetFileReader.java:167)
        at com.github.mmolimar.kafka.connect.fs.file.reader.ParquetFileReader$GenericRecordToStruct.apply(ParquetFileReader.java:157)
        at com.github.mmolimar.kafka.connect.fs.file.reader.AbstractFileReader.next(AbstractFileReader.java:44)
        at com.github.mmolimar.kafka.connect.fs.FsSourceTask.lambda$poll$0(FsSourceTask.java:76)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at com.github.mmolimar.kafka.connect.fs.FsSourceTask.poll(FsSourceTask.java:71)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmolimar** [comment]
Hi! Which version of CP are you using? Does it match with the connector?

**Comment by jkulzick** [comment]
Hi! Thanks for the quick response. We're on version 0.2-SNAPSHOT for the connector and version 3.3.0 for Confluent. Based on pom.xml should we be on 3.1.1 for Confluent?

**Comment by mmolimar** [comment]
Yes, or maybe you could change the CP version in the pom.xml file.

**Comment by jkulzick** [comment]
I tried changing the CP version in the pom.xml file and still received the same error. So then I started over with CP version 3.1.1 and connector version 0.1.2. I hit a different error (see below). I also tried with connector version 0.2-SNAPSHOT and hit the same error.

```
java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.<init>(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;Ljava/lang/Object;)V
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:248)
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:231)
	at org.apache.parquet.avro.AvroReadSupport.prepareForRead(AvroReadSupport.java:124)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:175)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:149)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:125)
	at com.github.mmolimar.kafka.connect.fs.file.reader.ParquetFileReader.hasNext(ParquetFileReader.java:78)
	at com.github.mmolimar.kafka.connect.fs.FsSourceTask.lambda$poll$0(FsSourceTask.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.github.mmolimar.kafka.connect.fs.FsSourceTask.poll(FsSourceTask.java:71)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmolimar** [comment]
There is a mismatch between library versions. Which versions of avro and parquet-avro libs do you have in the CP classpath?

**Comment by jkulzick** [comment]
I believe CP 3.1.1 uses avro 1.7.7 which has an earlier version of the Field method.

I'm not explicitly setting `CLASSPATH`. I added a symbolic link to the CONFLUENT_HOME/share/java/kafka-connect-fs pointing to /myinstallpath/kafka-connect-fs/target/kafka-connect-fs-0.2-SNAPSHOT-package/share/java/kafka-connect-fs.

**Comment by jkulzick** [comment]
FYI, I got this to work with CP 3.3.0 and connector 0.1.2 by doing the following:

1. updated pom.xml and changed scope of artifactId avro to provided
2. rebuilt package by specifying the following properties via command line:
'-Dconfluent.version=3.3.0' '-Davro.version=1.8.2' '-Dkafka.version=0.11.0.0-cp1'

**Comment by mmolimar** [comment]
Cool. The avro lib version which I'm using in the project is 1.8.1 (you can see that in the pom.xml)

**Comment by canyousayyes** [comment]
Hello,

I just encountered the same problem and this issue saved my day!

For reference, I am using CP 4.0.0 and updated the pom.xml to

```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kafka.version>1.0.0-cp1</kafka.version>
        <confluent.version>4.0.0</confluent.version>
        <hadoop.version>2.9.0</hadoop.version>
        <avro.version>1.8.2</avro.version>
        ...
    </properties>
    ...
        <dependency>
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
            <version>${avro.version}</version>
            <scope>provided</scope>
        </dependency>
```

It would also be nice to provide a more detailed steps on how to package on the repo README.
