### ISSUE TITLE
Got UnsupportedFileSystemException when using SFTP

### ISSUE THREAD

**Issue by o3661606** [mmolimar/kafka-connect-fs#19]
Below is my configuration
```
name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
fs.uris=sftp://root:password@<MY_IP_ADDR>:22/home/test
topic=connect-fs-source
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
policy.recursive=true
policy.regexp=^.*\.txt$
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader
```

But I got this:
```
[2017-12-18 17:21:28,093] ERROR Couldn't start FsSourceConnector: (com.github.mmolimar.kafka.connect.fs.FsSourceTask:57)
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "sftp"
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3220)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3240)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:121)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3291)
        at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:3265)
        at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:523)
        at com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.configFs(AbstractPolicy.java:69)
        at com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.<init>(AbstractPolicy.java:50)
        at com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy.<init>(SimplePolicy.java:11)
...
```

**Comment by mmolimar** [comment]
Hi,
Could you try including this property?
policy.fs.fs.sftp.impl=org.apache.hadoop.fs.sftp.SFTPFileSystem

**Comment by mmolimar** [comment]
Did you try that? I'd like to close this issue.

**Comment by o3661606** [comment]
Issue fixed by setting:
`policy.fs.fs.sftp.impl=org.apache.hadoop.fs.sftp.SFTPFileSystem
`

**Comment by selimelawwa** [comment]
@o3661606 where do I set this property?

**Comment by o3661606** [comment]
> @o3661606 where do I set this property?

I haven't use this for a while; as far as I remember, it is set in`kafka-connect-fs.properties`.
