### ISSUE TITLE
Support ByteArrayConverter

### ISSUE THREAD

**Issue by youngboy** [mmolimar/kafka-connect-fs#20]
[ByteArrayConverter](https://cwiki.apache.org/confluence/display/KAFKA/KIP-128%3A+Add+ByteArrayConverter+for+Kafka+Connect)

My case is to use `FileTextReader` to mirroring files from s3, but unfortunately if I set `kafka-connect`'s setting with
```
CONNECT_KEY_CONVERTER=org.apache.kafka.connect.converters.ByteArrayConverter
CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.converters.ByteArrayConverter
```
this connector would raise error

```
kafka-connect_1     | [2017-12-22 06:39:10,094] ERROR WorkerSourceTask{id=s3-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
kafka-connect_1     | org.apache.kafka.connect.errors.DataException: Invalid schema type for ByteArrayConverter: STRUCT
kafka-connect_1     | 	at org.apache.kafka.connect.converters.ByteArrayConverter.fromConnectData(ByteArrayConverter.java:39)
kafka-connect_1     | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:220)
kafka-connect_1     | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:187)
kafka-connect_1     | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
kafka-connect_1     | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
kafka-connect_1     | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
kafka-connect_1     | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kafka-connect_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
kafka-connect_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
kafka-connect_1     | 	at java.lang.Thread.run(Thread.java:745)
```

Just asking if it gonna support it ? or do I missing something here ?

**Comment by youngboy** [comment]
Updates, not a java programmer but I got my support by

set connector's
```
"file_reader.text.field_name.value": "bytearray"
```

and change `FsSourceTask.convert` function as
```
    private SourceRecord convert(FileMetadata metadata, Offset offset, Struct struct) {
        String fieldName = struct.schema().fields().get(0).name();

        if (fieldName.equals("bytearray")) {
            return new SourceRecord(
                    new HashMap<String, Object>() {
                        {
                            put("path", metadata.getPath());
                            //TODO manage blocks
                            //put("blocks", metadata.getBlocks().toString());
                        }
                    },
                    Collections.singletonMap("offset", offset.getRecordOffset()),
                    config.getTopic(),
                    Schema.BYTES_SCHEMA,
                    struct.get(fieldName).toString().getBytes()
            );
        }
        return new SourceRecord(
                new HashMap<String, Object>() {
                    {
                        put("path", metadata.getPath());
                        //TODO manage blocks
                        //put("blocks", metadata.getBlocks().toString());
                    }
                },
                Collections.singletonMap("offset", offset.getRecordOffset()),
                config.getTopic(),
                struct.schema(),
                struct
        );
    }

```

**Comment by mmolimar** [comment]
Did it work?

**Comment by youngboy** [comment]
It was works for me, but it is a long time ago.

Anyway I think we can close this issue.
