### ISSUE TITLE
S3 source connector

### ISSUE THREAD

**Issue by schhor** [mmolimar/kafka-connect-fs#26]
Hi,

I'm trying to use kafka-connect-fs to source from AWS S3 and I have an issue.

here my configuration file 
```
name=AIH_SourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
fs.uris=s3://XXXX/XXXX/
policy.fs.fs.s3a.access.key=XXXX
policy.fs.fs.s3a.secret.key=XXXX
topic=AIH_SOURCE
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
policy.recursive=false
policy.regexp=.*
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.DelimitedTextFileReader
file_reader.delimited.token=;
file_reader.delimited.header=true
``` 

but when I check the status of my connector with ```./confluent status connectors```, I have this response:

```
{  
   "name":"AIH_SourceConnector",
   "connector":{  
      "state":"RUNNING",
      "worker_id":"10.0.0.166:8083"
   },
   "tasks":[  
      {  
         "state":"FAILED",
         "trace":"org.apache.kafka.connect.errors.ConnectException: A problem has occurred reading configuration:org/apache/commons/lang/reflect/ConstructorUtils\n\tat com.github.mmolimar.kafka.connect.fs.FsSourceTask.start(FsSourceTask.java:58)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:157)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n",
         "id":0,
         "worker_id":"10.0.0.166:8083"
      }
   ],
   "type":"source"
}
```

here a focus on the stacktrace 

```
org.apache.kafka.connect.errors.ConnectException: A problem has occurred reading configuration:org/apache/commons/lang/reflect/ConstructorUtils\n\t
at com.github.mmolimar.kafka.connect.fs.FsSourceTask.start(FsSourceTask.java:58)\n\t
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:157)\n\t
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\t
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\t
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\t
at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\t
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\t
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\t
at java.lang.Thread.run(Thread.java:748)\n
```

**Do I miss something I my configuration ?**

There is a way to better see what happens (log) ?

Additional information:
- I have package your plugins using mvn clean package from master branch
- I have install your plugins by adding the generated jar on my kafka confluent platform and it is list as installed connector.
- I am using Open source Confluent Kafka 4.0.0
- I have try to change my fs.uris=s3://XXXX/XXXX/ into fs.uris=s3a://XXXX/XXXX/, but nothing better.
- I am pretty new to Kafka.

Thanks

**Comment by boboldehampsink** [comment]
I'm seeing the same problem:

```
{
    "name": "s3-tracks-playback",
    "connector": {
        "state": "RUNNING",
        "worker_id": "kafka-connect:8083"
    },
    "tasks": [
        {
            "state": "FAILED",
            "trace": "org.apache.kafka.connect.errors.ConnectException: A problem has occurred reading configuration:org/jets3t/service/S3ServiceException\n\tat com.github.mmolimar.kafka.connect.fs.FsSourceTask.start(FsSourceTask.java:58)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:157)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n",
            "id": 0,
            "worker_id": "kafka-connect:8083"
        }
    ],
    "type": "source"
}
```

**Comment by boboldehampsink** [comment]
The same error is mentioned in #20

**Comment by boboldehampsink** [comment]
I got it fixed by using the s3a protocol and environment variables.

**Comment by schhor** [comment]
Hi, after some search, it appears that S3a protocol is a hadoop one that alows usage of AWS S3. I'm not using Hadoop here, so I think I should find another solution to read data from S3 storage.

Thanks for the answer.

**Comment by mmolimar** [comment]
Yes, the connector uses the Hadoop File System API to read the file systems.
