### ISSUE TITLE
 java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map; (org.eclipse.jetty.util.component.AbstractLifeCycle:212)

### ISSUE THREAD

**Issue by revinjchalil** [mmolimar/kafka-connect-fs#3]
I am seeing the  java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map; (org.eclipse.jetty.util.component.AbstractLifeCycle:212), when executing the below.

/usr/bin/connect-standalone /etc/schema-registry/connect-avro-standalone.properties /etc/kafka/kafka-connect-fs.properties

I am not sure if this can be the cause but I checked under package and have v1.9 of both jersey-core & jersey-client jars. 

Thanks.

**Comment by revinjchalil** [comment]
below are the details. 

[2017-05-06 23:07:39,609] WARN FAILED o.e.j.s.ServletContextHandler@7b94089b{/,null,STARTING}: java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map; (org.eclipse.jetty.util.component.AbstractLifeCycle:212)
java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:331)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
        at javax.servlet.GenericServlet.init(GenericServlet.java:241)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:232)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.apache.kafka.connect.runtime.rest.RestServer.start(RestServer.java:145)
        at org.apache.kafka.connect.runtime.Connect.start(Connect.java:54)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:81)

**Comment by mmolimar** [comment]
Hi Revin,

Could you share the content of the both properties file? Which version of the CP and the kafka-connect-fs are you using?

**Comment by revinjchalil** [comment]
Hi Mario,

Please see the contents of properties file below. 

connect-avro-standalone.properties
---------------------------------------
bootstrap.servers=localhost:9092
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets

kafka-connect-fs.properties
------------------------------
name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
fs.uris=s3://abc-def-xyz-dev/spark/conf/stream_config.cfg
topic=qubole
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
policy.recursive=true
policy.regexp=^[0-9]*\.txt$
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader

I am using v3.2 of CP and kafka-connect-fs-0.2-SNAPSHOT-package. 

Thanks:
Revin

**Comment by mmolimar** [comment]
There was an issue with the dependencies because avro-tools was including jsr311-api in its jar file.
Now it's working on a new [release](https://github.com/mmolimar/kafka-connect-fs/releases/tag/v0.1.1.1).
Could you try it again?

Thanks

**Comment by revinjchalil** [comment]
Thanks. It went past that failure point but fails with the AWS Credentials
error. My source files (fs.uris) are at s3a://. Are the access_key and
secret_key expected in the properties file?

I tried with

export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...


but didn't work.

Below is the details.

[2017-05-09 04:57:52,187] INFO SimplePolicy values:
        policy.regexp = ^[0-9]*.txt$
        policy.class =
com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
        policy.recursive = true
 (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:253)
[2017-05-09 04:57:52,600] WARN Unable to load native-hadoop library for
your platform... using builtin-java classes where applicable
(org.apache.hadoop.util.NativeCodeLoader:62)
[2017-05-09 04:57:53,318] ERROR Couldn't start FsSourceConnector:
(com.github.mmolimar.kafka.connect.fs.FsSourceTask:57)
com.amazonaws.AmazonClientException: Unable to load AWS credentials from
any provider in the chain
        at
com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
        at
com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3521)
        at
com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1031)
        at
com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:994)
        at
org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:297)
        at
org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at
org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at
org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:2691)
        at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:420)
        at
com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.configFs(AbstractPolicy.java:69)
        at
com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.<init>(AbstractPolicy.java:50)
        at
com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy.<init>(SimplePolicy.java:11)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native
Method)
        at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at
com.github.mmolimar.kafka.connect.fs.util.ReflectionUtils.make(ReflectionUtils.java:34)
        at
com.github.mmolimar.kafka.connect.fs.util.ReflectionUtils.makePolicy(ReflectionUtils.java:23)
        at
com.github.mmolimar.kafka.connect.fs.FsSourceTask.start(FsSourceTask.java:52)
        at
org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:141)
        at
org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at
org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-05-09 04:57:53,321] ERROR Task FsSourceConnector-0 threw an uncaught
and unrecoverable exception
(org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.connect.errors.ConnectException: A problem has ocurred
reading configuration:Unable to load AWS credentials from any provider in
the chain
        at
com.github.mmolimar.kafka.connect.fs.FsSourceTask.start(FsSourceTask.java:58)
        at
org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:141)
        at
org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at
org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mmolimar** [comment]
I think you should set these properties in the kafka-connect-fs.properties file:

policy.fs.fs.s3a.access.key=<ACCESS_KEY>
policy.fs.fs.s3a.secret.key=<SECRET_KEY>

Also you can set more custom FS configurations. These properties are in this class: org.apache.hadoop.fs.s3a.Constants

The prefix 'policy.fs.' is used in order to customize your FS config. You can find more info [here](http://kafka-connect-fs.readthedocs.io/en/latest/config_options.html#policies).

**Comment by revinjchalil** [comment]
Thanks Mario. I have added the properties you mentioned in kafka-connect-fs.properties file and it is not failing now. However, for some reason, I am not getting the messages on the kafka-consumer. I have tried adding new files under the S3 uri, that was specified in the properties file but it does not seem to be getting published to Kafka Topic. 

I have a question: Is it expected that the incremental files added will be automatically published to kafka topic? 

Below are the steps i followed. 

- started schema registry
- started "connect-standalone" with the classpath set and with properties file
- started the kafka-avro-console-consumer (tried with kafka-console-consumer as well). 


Below are the logs from connect-standalone with kafka-connect-fs. 

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-serde-tools/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-elasticsearch/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[2017-05-09 19:04:33,959] INFO StandaloneConfig values:
        access.control.allow.methods =
        access.control.allow.origin =
        bootstrap.servers = [localhost:9092]
        internal.key.converter = class org.apache.kafka.connect.json.JsonConverter
        internal.value.converter = class org.apache.kafka.connect.json.JsonConverter
        key.converter = class io.confluent.connect.avro.AvroConverter
        offset.flush.interval.ms = 60000
        offset.flush.timeout.ms = 5000
        offset.storage.file.filename = /tmp/connect.offsets
        rest.advertised.host.name = null
        rest.advertised.port = null
        rest.host.name = null
        rest.port = 8083
        task.shutdown.graceful.timeout.ms = 5000
        value.converter = class io.confluent.connect.avro.AvroConverter
 (org.apache.kafka.connect.runtime.standalone.StandaloneConfig:180)
[2017-05-09 19:04:34,100] INFO Logging initialized @715ms (org.eclipse.jetty.util.log:186)
[2017-05-09 19:04:34,380] INFO AvroConverterConfig values:
        schema.registry.url = [http://localhost:8081]
        max.schemas.per.subject = 1000
 (io.confluent.connect.avro.AvroConverterConfig:169)
[2017-05-09 19:04:34,563] INFO AvroDataConfig values:
        schemas.cache.config = 1000
        enhanced.avro.schema.support = false
        connect.meta.data = true
 (io.confluent.connect.avro.AvroDataConfig:169)
[2017-05-09 19:04:34,565] INFO AvroConverterConfig values:
        schema.registry.url = [http://localhost:8081]
        max.schemas.per.subject = 1000
 (io.confluent.connect.avro.AvroConverterConfig:169)
[2017-05-09 19:04:34,565] INFO AvroDataConfig values:
        schemas.cache.config = 1000
        enhanced.avro.schema.support = false
        connect.meta.data = true
 (io.confluent.connect.avro.AvroDataConfig:169)
[2017-05-09 19:04:34,578] INFO Kafka Connect starting (org.apache.kafka.connect.runtime.Connect:50)
[2017-05-09 19:04:34,578] INFO Herder starting (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:72)
[2017-05-09 19:04:34,578] INFO Worker starting (org.apache.kafka.connect.runtime.Worker:119)
[2017-05-09 19:04:34,579] INFO Starting FileOffsetBackingStore with file /tmp/connect.offsets (org.apache.kafka.connect.storage.FileOffsetBackingStore:60)
[2017-05-09 19:04:34,584] INFO Worker started (org.apache.kafka.connect.runtime.Worker:124)
[2017-05-09 19:04:34,584] INFO Herder started (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:74)
[2017-05-09 19:04:34,585] INFO Starting REST server (org.apache.kafka.connect.runtime.rest.RestServer:98)
[2017-05-09 19:04:34,747] INFO jetty-9.2.15.v20160210 (org.eclipse.jetty.server.Server:327)
May 09, 2017 7:04:35 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

[2017-05-09 19:04:35,848] INFO Started o.e.j.s.ServletContextHandler@210386e0{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:744)
[2017-05-09 19:04:35,891] INFO Started ServerConnector@263e27bb{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:266)
[2017-05-09 19:04:35,893] INFO Started @2511ms (org.eclipse.jetty.server.Server:379)
[2017-05-09 19:04:35,894] INFO REST server listening at http://x.x.x.x:8083/, advertising URL http://x.x.x.x:8083/ (org.apache.kafka.connect.runtime.rest.RestServer:150)
[2017-05-09 19:04:35,894] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:56)
[2017-05-09 19:04:35,904] INFO ConnectorConfig values:
        connector.class = com.github.mmolimar.kafka.connect.fs.FsSourceConnector
        key.converter = null
        name = FsSourceConnector
        tasks.max = 1
        transforms = null
        value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig:180)
[2017-05-09 19:04:35,905] INFO Creating connector FsSourceConnector of type com.github.mmolimar.kafka.connect.fs.FsSourceConnector (org.apache.kafka.connect.runtime.Worker:178)
[2017-05-09 19:04:35,908] INFO Instantiated connector FsSourceConnector with version 0.1.1.1 of type class com.github.mmolimar.kafka.connect.fs.FsSourceConnector (org.apache.kafka.connect.runtime.Worker:181)
[2017-05-09 19:04:35,909] INFO Starting FsSourceConnector... (com.github.mmolimar.kafka.connect.fs.FsSourceConnector:34)
[2017-05-09 19:04:35,910] INFO FsSourceConnectorConfig values:
        fs.uris = [s3a://expedia-risk-data-code-dev/spark/conf/]
        topic = qubole
 (com.github.mmolimar.kafka.connect.fs.FsSourceConnectorConfig:180)
[2017-05-09 19:04:35,912] INFO Finished creating connector FsSourceConnector (org.apache.kafka.connect.runtime.Worker:194)
[2017-05-09 19:04:35,912] INFO SourceConnectorConfig values:
        connector.class = com.github.mmolimar.kafka.connect.fs.FsSourceConnector
        key.converter = null
        name = FsSourceConnector
        tasks.max = 1
        transforms = null
        value.converter = null
 (org.apache.kafka.connect.runtime.SourceConnectorConfig:180)
[2017-05-09 19:04:35,926] INFO Creating task FsSourceConnector-0 (org.apache.kafka.connect.runtime.Worker:305)
[2017-05-09 19:04:35,927] INFO ConnectorConfig values:
        connector.class = com.github.mmolimar.kafka.connect.fs.FsSourceConnector
        key.converter = null
        name = FsSourceConnector
        tasks.max = 1
        transforms = null
        value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig:180)
[2017-05-09 19:04:35,928] INFO TaskConfig values:
        task.class = class com.github.mmolimar.kafka.connect.fs.FsSourceTask
 (org.apache.kafka.connect.runtime.TaskConfig:180)
[2017-05-09 19:04:35,928] INFO Instantiated task FsSourceConnector-0 with version 0.1.1.1 of type com.github.mmolimar.kafka.connect.fs.FsSourceTask (org.apache.kafka.connect.runtime.Worker:317)
[2017-05-09 19:04:35,948] INFO ProducerConfig values:
        acks = all
        batch.size = 16384
        block.on.buffer.full = false
        bootstrap.servers = [localhost:9092]
        buffer.memory = 33554432
        client.id =
        compression.type = none
        connections.max.idle.ms = 540000
        interceptor.classes = null
        key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
        linger.ms = 0
        max.block.ms = 9223372036854775807
        max.in.flight.requests.per.connection = 1
        max.request.size = 1048576
        metadata.fetch.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.ms = 50
        request.timeout.ms = 2147483647
        retries = 2147483647
        retry.backoff.ms = 100
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        timeout.ms = 30000
        value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
 (org.apache.kafka.clients.producer.ProducerConfig:180)
[2017-05-09 19:04:36,018] INFO Kafka version : 0.10.2.0-cp1 (org.apache.kafka.common.utils.AppInfoParser:83)
[2017-05-09 19:04:36,018] INFO Kafka commitId : 0003bb14a2acad37 (org.apache.kafka.common.utils.AppInfoParser:84)
[2017-05-09 19:04:36,038] INFO Created connector FsSourceConnector (org.apache.kafka.connect.cli.ConnectStandalone:90)
[2017-05-09 19:04:36,038] INFO FsSourceTaskConfig values:
        file_reader.class = class com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader
        fs.uris = [s3a://xxxx/yyyy/conf/]
        policy.class = class com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
        policy.recursive = true
        policy.regexp = ^[0-9]*.txt$
        topic = xxxx
 (com.github.mmolimar.kafka.connect.fs.FsSourceTaskConfig:180)
[2017-05-09 19:04:36,039] INFO FsSourceTaskConfig values:
        file_reader.class = class com.github.mmolimar.kafka.connect.fs.file.reader.TextFileReader
        fs.uris = [s3a://xxxx/yyyy/conf/]
        policy.class = class com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
        policy.recursive = true
        policy.regexp = ^[0-9]*.txt$
        topic = qubole
 (com.github.mmolimar.kafka.connect.fs.FsSourceTaskConfig:180)
[2017-05-09 19:04:36,064] INFO SimplePolicy values:
        policy.regexp = ^[0-9]*.txt$
        policy.class = com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
        policy.fs.fs.s3a.secret.key = xxxxx
        policy.fs.fs.s3a.access.key = yyyyy
        policy.recursive = true
 (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:253)
[2017-05-09 19:04:36,555] WARN Unable to load native-hadoop library for your platform... using builtin-java classes where applicable (org.apache.hadoop.util.NativeCodeLoader:62)
[2017-05-09 19:04:37,567] INFO Source task WorkerSourceTask{id=FsSourceConnector-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:142)
[2017-05-09 19:04:46,074] INFO Reflections took 11400 ms to scan 359 urls, producing 16379 keys and 116720 values  (org.reflections.Reflections:229)

**Comment by mmolimar** [comment]
In your connector config you have defined the property 'policy.regexp' with a regular expression to filter files from the FS. That might be the reason.

On the other hand, incremental files will be processed based on the offsets committed previously (if they were processed earlier), so yes :-). More info [here](http://kafka-connect-fs.readthedocs.io/en/latest/connector.html#policies)
