### ISSUE TITLE
Kafka-connect-fs with Azure Data Lake

### ISSUE THREAD

**Issue by tudormaz** [mmolimar/kafka-connect-fs#43]
Hello, 

I am currently trying to modify this connector to work with Azure Data Lake (which is based on HDFS). I did add the missing dependencies in pom.xml
```
<dependency>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-azure-datalake</artifactId>
  <version>${hadoop.version}</version>
</dependency>
<dependency>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-azure</artifactId>
  <version>${hadoop.version}</version>
</dependency>
```

My current configuration looks something like this
```
{
    "name": "uk-hdfs-se-search-metrics-source",
    "config": {
          "topic": "se.userprofile",
          "connector.class": "com.github.mmolimar.kafka.connect.fs.FsSourceConnector",
          "tasks.max": "1",
          "fs.uris": "adl://<datalakeinstance>.azuredatalakestore.net/<some_path/",
          "file_reader.class": "com.github.mmolimar.kafka.connect.fs.file.reader.DelimitedTextFileReader",
          "file_reader.delimited.token": ",",
          "file_reader.delimited.header": true,
          "policy.class": "com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy",
          "policy.recursive": "true",
          "files_2_read_in_a_record": 15,
          "policy.fs.fs.adl.impl": "org.apache.hadoop.fs.adl.AdlFileSystem",
          "hadoop.conf.dir": "/tmp/hdfs"
     }
}
```
I built this project, deployed it in my local Confluent Kafka deployment in the <confluent>/share/java/kafka-connect-fs/ as it is supposed to be done.

Did `curl -X PUT -H "Content-Type: application/json" --fail --data "$config" http://localhost:8083/connectors/$connector/config` to instantiate it. 
But, I get the following error:
```
java.io.IOException: Password fs.adl.oauth2.client.id not found
	at org.apache.hadoop.fs.adl.AdlFileSystem.getPasswordString(AdlFileSystem.java:997)
	at org.apache.hadoop.fs.adl.AdlFileSystem.getConfCredentialBasedTokenProvider(AdlFileSystem.java:279)
	at org.apache.hadoop.fs.adl.AdlFileSystem.getAccessTokenProvider(AdlFileSystem.java:258)
	at org.apache.hadoop.fs.adl.AdlFileSystem.initialize(AdlFileSystem.java:163)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3242)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:121)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3291)
	at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:3265)
	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:523)
	at com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.configFs(AbstractPolicy.java:73)
	at com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.<init>(AbstractPolicy.java:50)
	at com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy.<init>(SimplePolicy.java:11)
```

I did something similar a couple of months ago with the Confluent HDFS sink connector and that one had the property "hadoop.conf.dir": "/tmp/hdfs" where I defined the core-site.xml and hdfs-site.xml files with my credentials like it is specified in https://hadoop.apache.org/docs/current/hadoop-azure-datalake/index.html 
Is there someway to define it for this connector also?

The major part of the credentials config is done in core-site.xml which looks like this
<property>
  <name>fs.adl.oauth2.access.token.provider.type</name>
  <value>ClientCredential</value>
</property>

<property>
  <name>fs.adl.oauth2.refresh.url</name>
  <value>TOKEN ENDPOINT FROM STEP 7 ABOVE</value>
</property>

<property>
  <name>fs.adl.oauth2.client.id</name>
  <value>CLIENT ID FROM STEP 7 ABOVE</value>
</property>

<property>
  <name>fs.adl.oauth2.credential</name>
  <value>PASSWORD FROM STEP 7 ABOVE</value>
</property>

Are these supposed to be defined as "fs.fs.adl.oauth2.access.token.provider.type": "some value" (etc) in my JSON?

Kind regards,
Tudor

**Comment by tudormaz** [comment]
Hello again, 

I was right, I did have to configure those properties and bypass the core-site.xml stuff
"policy.fs.fs.adl.oauth2.access.token.provider.type": "ClientCredential",
"policy.fs.fs.adl.oauth2.refresh.url": "https://login.microsoftonline.com/\<subscription-id\>/oauth2/token",
"policy.fs.fs.adl.oauth2.client.id": "\<client-id\>",
"policy.fs.fs.adl.oauth2.credential": "\<client-secret\>",
          

[2018-09-07 12:04:02,114] INFO [Producer clientId=producer-5] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1103)
[2018-09-07 12:04:02,543] INFO fileStatus.getPath() adl://\<datalakeinstance\>.azuredatalakestore.net/\<some-path\>/hdfs-source-test.csv (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:228)
[2018-09-07 12:04:02,543] INFO fileStatus.getModificationTime 1536153279385 (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:229)
[2018-09-07 12:04:02,543] INFO ============ getMaxModificationTime(incomingFiles) ============ (com.github.mmolimar.kafka.connect.fs.FsSourceTask:130)
[2018-09-07 12:04:02,543] INFO ========== incomingFiles.size ======================= 1 (com.github.mmolimar.kafka.connect.fs.FsSourceTask:131)
[2018-09-07 12:04:02,543] INFO fileMetadata.getPath() adl://\<datalakeinstance\>.azuredatalakestore.net/\<some-path\>/hdfs-source-test.csv (com.github.mmolimar.kafka.connect.fs.FsSourceTask:112)
[2018-09-07 12:04:02,543] INFO fileMetadata.getModificationTime() 1536153279385 (com.github.mmolimar.kafka.connect.fs.FsSourceTask:113)
[2018-09-07 12:04:02,543] INFO Size of this.files before processing 1 (com.github.mmolimar.kafka.connect.fs.FsSourceTask:71)
[2018-09-07 12:04:02,543] INFO interrupted: false (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:208)
[2018-09-07 12:04:02,544] INFO getExecutions(): 1 (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:209)
[2018-09-07 12:04:02,544] INFO interrupted: false (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:208)
[2018-09-07 12:04:02,544] INFO getExecutions(): 1 (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:209)
[2018-09-07 12:04:02,545] ERROR Cannot retrive files to process from FS: [adl://\<datalakeinstance\>.azuredatalakestore.net/\<some-path\>]. Keep going... (com.github.mmolimar.kafka.connect.fs.FsSourceTask:163)
org.apache.kafka.connect.errors.IllegalWorkerStateException: Policy has ended. Cannot be retried
	at com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.execute(AbstractPolicy.java:134)
	at com.github.mmolimar.kafka.connect.fs.FsSourceTask.updateFiles2Process(FsSourceTask.java:124)
	at com.github.mmolimar.kafka.connect.fs.FsSourceTask.poll(FsSourceTask.java:69)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-09-07 12:04:02,545] INFO Size of this.files before processing 0 (com.github.mmolimar.kafka.connect.fs.FsSourceTask:71)
[2018-09-07 12:04:02,545] INFO interrupted: false (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:208)
[2018-09-07 12:04:02,545] INFO getExecutions(): 1 (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:209)
[2018-09-07 12:04:02,546] INFO interrupted: false (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:208)
[2018-09-07 12:04:02,546] INFO getExecutions(): 1 (com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy:209)

Currently, I'm trying to debug this. So far, haven't made any real progress on this. 
If you have any ideas, please let me know.

Kind regards,
Tudor

**Comment by tudormaz** [comment]
Hello again, 

I managed to make this run by adding the following properties:
```
"policy.fs.fs.adl.impl": "org.apache.hadoop.fs.adl.AdlFileSystem",
"policy.fs.fs.adl.oauth2.access.token.provider.type": "ClientCredential",
"policy.fs.fs.adl.oauth2.refresh.url": "",
"policy.fs.fs.adl.oauth2.client.id": "",
"policy.fs.fs.adl.oauth2.credential": "",
```
It did pickup my CSV files from the ADL instance and place it in my Kafka topic as Avro objects, with my specified schema.

Kind regards,
Tudor
