### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/lang/reflect/ConstructorUtils

### ISSUE THREAD

**Issue by Vesli** [mmolimar/kafka-connect-fs#49]
Hello, 

Following this config after freshly cloning & compiling your code:

```
name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
fs.uris=file:///Users/me/a/path/tofolder/with/files
topic=ingestion
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SimplePolicy
policy.recursive=false
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.AgnosticFileReader
file_reader.agnostic.extensions.delimited=tsv,csv,pdf
```

I run:
bin/connect-standalone.sh config/connect-standalone.properties config/kafka-connect-fs.properties

but I stumble into this error:
```
[2020-01-10 13:54:00,582] ERROR Couldn't start FsSourceConnector: (com.github.mmolimar.kafka.connect.fs.FsSourceTask:57)
java.lang.NoClassDefFoundError: org/apache/commons/lang/reflect/ConstructorUtils
	at com.github.mmolimar.kafka.connect.fs.util.ReflectionUtils.make(ReflectionUtils.java:30)
	at com.github.mmolimar.kafka.connect.fs.util.ReflectionUtils.makePolicy(ReflectionUtils.java:23)
	at com.github.mmolimar.kafka.connect.fs.FsSourceTask.start(FsSourceTask.java:52)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:208)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.reflect.ConstructorUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more
[2020-01-10 13:54:00,583] INFO WorkerSourceTask{id=FsSourceConnector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2020-01-10 13:54:00,584] INFO WorkerSourceTask{id=FsSourceConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2020-01-10 13:54:00,584] ERROR WorkerSourceTask{id=FsSourceConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: A problem has occurred reading configuration:org/apache/commons/lang/reflect/ConstructorUtils
	at com.github.mmolimar.kafka.connect.fs.FsSourceTask.start(FsSourceTask.java:58)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:208)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

is there anything else to do in order to have this connector running?

**Comment by mmolimar** [comment]
Hello,
The dependencies are not included in the classpath... So you can build the connector jar including its dependencies -a fat jar- or just put the dependencies into de lib dir
