### ISSUE TITLE
Getting heap issue in the kafka FS source connector(Tag:-v0.2) code

### ISSUE THREAD

**Issue by krishnendudas1979** [mmolimar/kafka-connect-fs#78]
We are using Kafka FS source connector code of version v0.2 to read data from S3 and published into the Kafka topic. We just customize one small part in the function **AbstractPolicy:listFiles(FileSystem fs)**, to filter out files having last Modification date of more than 7 days.
`public boolean hasNext() {
                try {
                    if (current == null) {
                        if (!it.hasNext()) return false;
                        current = it.next();
                        return hasNext();
                    }
                    if (current.isFile() &&
                               //To avoid memory issue, we will select only those files whose
                               //last modification time is less that a configurable number of days old.
                               (dt - (current.getModificationTime()/(1000 * 3600 * 24)) < fileFilterDays) &&
                            fileRegexp.matcher(current.getPath().getName()).find()) {
                        return true;
                    }
                    current = null;
                    return hasNext();
                } catch (IOException ioe) {
                    throw new ConnectException(ioe);
                }
            }
`

Please find below the related information of the source connector's which is having issue:- 

1-->When we start this connector service, in the first poll it got around 2500 files to be processed. Each file is having very less data (around 2 to 3 number of rows). Our poll frequency in 5 secs and in every poll we are getting around 2500 to 3000 files for processing.

2-->There are 16 connector's running under a worker service which is running in a distrusted mode under a cluster of two nodes. 

3-->Each source connector is reading form a unique S3 path ("fs.uris": "s3a://<bucket name>/InputFiles/MH/"). There can be multiple sub folders under this path according to the date 
(e.g. s3a://<bucket name>/InputFiles/MH/YYYY/MM/DD)

4-->It has been observed that, when the connector run for a duration of more than one hour and processing multiple files in successive polls, we got Out of Memory heap issue.
    In the connector's log we got below exception,
[2020-11-10 18:28:32,461] | ERROR | An error has occurred when creating reader for file (com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy)|[FT-pullConnector|task-0]
[2020-11-10 18:28:32,461] | ERROR | java.lang.OutOfMemoryError: Java heap space (com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy)|[FT-pullConnector|task-0]
[2020-11-10 18:28:32,461] | WARN | FSLOGFileConnector | MINOR | 2057 | A problem occurred while creating reader for s3a://test-bucket/InputFiles/MH/2020/11/10/test_file_20201109131417475_9.csv. Keep going... | An error has occurred when creating reader for file: s3a://test-bucket/InputFiles/MH/2020/11/10/test_file_20201109131417475_9.csv (com.github.mmolimar.kafka.connect.fs.FsSourceTask)|[FT-pullConnector|task-0]
org.apache.kafka.connect.errors.ConnectException: An error has occurred when creating reader for file: s3a://test-bucket/InputFiles/MH/2020/11/10/test_file_20201109131417475_9.csv
        at com.github.mmolimar.kafka.connect.fs.policy.AbstractPolicy.offer(AbstractPolicy.java:238)
        at com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy.offer(SleepyPolicy.java:11)
        at com.github.mmolimar.kafka.connect.fs.FsSourceTask.poll(FsSourceTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:259)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:226)
		 at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
**Caused by: java.lang.OutOfMemoryError: Java heap space**
[2020-11-10 18:28:32,461] | ERROR | WorkerSourceTask{id=FT-pullConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)|[FT-pullConnector|task-0]
**java.lang.OutOfMemoryError: Java heap space**
        at java.util.HashMap.resize(HashMap.java:704)
        at java.util.HashMap.putVal(HashMap.java:629)
        at java.util.HashMap.put(HashMap.java:612)
        at java.util.HashSet.add(HashSet.java:220)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at sun.security.ssl.SSLAlgorithmDecomposer.decomposes(SSLAlgorithmDecomposer.java:149)
        at sun.security.ssl.SSLAlgorithmDecomposer.decompose(SSLAlgorithmDecomposer.java:222)
        at sun.security.ssl.SSLAlgorithmDecomposer.decompose(SSLAlgorithmDecomposer.java:244)
        at sun.security.util.AbstractAlgorithmConstraints.checkAlgorithm(AbstractAlgorithmConstraints.java:95)
        at sun.security.util.DisabledAlgorithmConstraints.permits(DisabledAlgorithmConstraints.java:110)
        at sun.security.ssl.SSLAlgorithmConstraints.permits(SSLAlgorithmConstraints.java:144)
        at sun.security.ssl.Handshaker.getActiveCipherSuites(Handshaker.java:694)
		       at sun.security.ssl.Handshaker.activate(Handshaker.java:560)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1495)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
        at com.amazonaws.thirdparty.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
        at com.amazonaws.thirdparty.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
        at com.amazonaws.thirdparty.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy40.connect(Unknown Source)
        at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at com.amazonaws.thirdparty.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
		   at com.amazonaws.thirdparty.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[2020-11-10 18:28:32,461] | ERROR | WorkerSourceTask{id=FT-pullConnector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)|[FT-pullConnector|task-0]

5-->jstat -gccause 329929  5000
  S0     S1     E      **O**      M     CCS    	YGC    YGCT    FGC    FGCT     GCT    LGCC                 GCC   
  0.00   0.00   0.00 **100.00**  96.79  93.35   1155   21.817   181  642.268  664.085 No GC                Allocation Failure
  0.00   0.00   0.00 **100.00**  96.79  93.35   1157   21.824   183  649.372  671.196 No GC                Allocation Failure
  0.00   0.00   0.00 **100.00**  96.79  93.35   1159   21.830   184  652.918  674.748 No GC                Allocation Failure
  0.00   0.00   0.00 **100.00**  96.79  93.35   1159   21.830   185  656.454  678.284 No GC                Allocation Failure
  0.00   0.00   0.00 **100.00**  96.79  93.35   1161   21.836   187  663.553  685.389 No GC                Allocation Failure
  0.00   0.00   0.00 **100.00**  96.79  93.35   1162   21.840   188  667.097  688.936 No GC                Allocation Failure
  0.00   0.00   0.00 **100.00**  96.79  93.35   1164   21.847   190  674.196  696.043 No GC                Allocation Failure
  0.00   0.00   0.00  **99.98**  96.79  93.35   1165   21.854   191  677.739  699.593 No GC                Allocation Failure
  0.00   0.00   0.00  **99.98**  96.79  93.35   1167   21.864   192  681.918  703.781 No GC                Allocation Failure
  0.00   0.00   0.00  **99.96**  96.85  93.44   1171   21.890   194  689.069  710.960 No GC                Allocation Failure
  0.00   0.00   0.00  **99.98**  96.85  93.45   1172   21.895   195  692.655  714.550 No GC                Allocation Failure
  0.00   0.00   0.00 **100.00**  96.89  93.48   1174   21.910   196  696.235  718.146 No GC                Allocation Failure
  0.00   0.00   4.76  **72.19**  97.03  93.63   1179   22.042   197  702.365  724.407 Allocation Failure   No GC

**Comment by mmolimar** [comment]
Hi!

It looks like you're processing the same files over and over again due to the frequency is 5 secs and the files are getting queued. Which is your config for committing offsets? Maybe it could work better increasing this frequency (> commit offset interval).

On the other hand, have you tried with a newer version? In the latest versions, you can set the batch size to manage this such amount of files and some other improvements.
